apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-inspire
spec:
    replicas: 3
    selector:
        matchLabels:
            app: my-inspire
    template:
        metadata:
            labels:
                app: my-inspire
        spec:
            containers:
            - name: myInspire-app
              image: deepshikhadubey/my-inspire:v1
              ports:
              - containerPort: 5000              
