name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-web-server .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Test step
      run: docker run -d -p 5000:5000 my-web-server

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Deploy step
      run: echo "Deploying application..."

             
