name: CI/CD Pipeline
on:
    push:
         branches: [ "main" ]

jobs:

      build:
           runs-on: ubuntu-latest
           steps:
           - name: Checkout code
             uses: actions/checkout@v2
           - name: Build Docker image
             run: docker build -t my-web-server .
           - name: Test Docker Image
             run: echo "Running tests..."
           - name: Deploy Docker Container
             run: docker run -d -p 5000:5000 my-web-server
