name: Scalable-Application CI pipeline
on: 
   push:
      paths:
         - 'Project-8-Build-Scalable-Application-with-K8s-Docker'
jobs:         
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Checkout code
              uses: actions/setup-python@v2
              
              with:
                python-version: '3.9'
            - name: Install dependencies
              run: |
                 cd Project-8-Build-Scalable-Application-with-K8s-Docker
                 pip install -r requirements.txt
            - name: Run test cases on code commits
              run: pytest 
